// <auto-generated />
using Garages.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Garages.Data.Migrations
{
    [DbContext(typeof(GarageDbContext))]
    [Migration("20251130222553_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Garages.Data.Garage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CodMiktzoa")
                        .HasColumnType("integer");

                    b.Property<int>("CodSugMosah")
                        .HasColumnType("integer");

                    b.Property<string>("Ktovet")
                        .HasColumnType("text");

                    b.Property<string>("MenahelMiktzoa")
                        .HasColumnType("text");

                    b.Property<string>("Miktzoa")
                        .HasColumnType("text");

                    b.Property<int>("Mikud")
                        .HasColumnType("integer");

                    b.Property<int>("MisparMosah")
                        .HasColumnType("integer");

                    b.Property<long>("RashamHavarot")
                        .HasColumnType("bigint");

                    b.Property<string>("ShemMosah")
                        .HasColumnType("text");

                    b.Property<string>("SugMosah")
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .HasColumnType("text");

                    b.Property<string>("Testime")
                        .HasColumnType("text");

                    b.Property<string>("Yishuv")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Garages");
                });
#pragma warning restore 612, 618
        }
    }
}
