// <auto-generated />
using Garages.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Garages.Data.Migrations
{
    [DbContext(typeof(GarageDbContext))]
    partial class GarageDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Garages.Data.Garage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("TESTIME")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("cod_miktzoa")
                        .HasColumnType("integer");

                    b.Property<int>("cod_sug_mosah")
                        .HasColumnType("integer");

                    b.Property<string>("ktovet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("menahel_miktzoa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("miktzoa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("mikud")
                        .HasColumnType("integer");

                    b.Property<int>("mispar_mosah")
                        .HasColumnType("integer");

                    b.Property<long>("rasham_havarot")
                        .HasColumnType("bigint");

                    b.Property<string>("shem_mosah")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sug_mosah")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("telephone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("yishuv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Garages");
                });
#pragma warning restore 612, 618
        }
    }
}
